server:
  servlet:
    jsp:
      init-parameters:
        development: true
  port: 8989

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?characterEncoding=UTF-8
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity